version: '3.9'

services:
  history_of_mine:
    container_name: history_of_mine
    image: finityex/bfit:latest
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://hom_db:5432/hom
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=wojtek
    depends_on:
      - hom_db
      - hom_pgadmin
  hom_db:
    container_name: hom_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: wojtek
      POSTGRES_USER: postgres
      POSTGRES_DB: hom
    volumes:
      - pgdata:/var/lib/postgresql/data
  hom_pgadmin:
    container_name: hom_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    depends_on:
      - hom_db
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
volumes:
  pgdata: {}
  pgadmin: {}