version: '3.9'

services:
  bfit:
    container_name: bfit
    image: finityex/bfit:latest
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://bfit_db:5432/bfit
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=wojtek
    depends_on:
      - bfit_db
      - bfit_pgadmin
  bfit_db:
    container_name: bfit_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: wojtek
      POSTGRES_USER: postgres
      POSTGRES_DB: bfit
    volumes:
      - pgdata:/var/lib/postgresql/data
  bfit_pgadmin:
    container_name: bfit_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    depends_on:
      - bfit_db
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
volumes:
  pgdata: {}
  pgadmin: {}